os: linux
dist: bionic
language: python
python:
    - "3.6"  # current default on Travis CI
before_install:
    - cd py_src
install:
    - python3 -m pip install Cython
    - python3 -m pip install -e ..[dev]
    # - python3 setup.py build_ext --inplace
script:
    - export MYPYPATH='./stubs'
    - mypy ../py_src
    - flake8 ../py_src
    - docstr-coverage -m -f -F 80.0 ../py_src
after_success:
    - cd ../test
    - export NUMBA_DISABLE_JIT=1
    - pytest --cov-config=.coveragerc --cov-report=xml --cov=../py_src
    - bash <(curl -s https://codecov.io/bash)
    - cd ..
    - python3 -c "import module1; import module2; import module3; import sub_module.module4; import extension1; print('success')"
    - python3 -m sub_module
    - test_pack_test

notifications:
    email: false
