os: linux
dist: bionic
language: python
python:
    - "3.6"  # current default on Travis CI
before_install:
    - cd py_src
install:
    - pip3 install -r requirements.txt
    - pip3 install -e ..
script:
    - export MYPYPATH='./stubs'
    - mypy ../py_src
after_success:
    - python3 -m pip install pytest-cov
    - cd ../test
    - py.test --cov-config=.coveragerc --cov-report=xml --cov=../py_src
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
