language: python
python:
    - "3.6"  # current default on Travis CI
before_install:
    - cd py_src
install:
    - pip3 install -r requirements.txt
    - pip3 install ..
script:
    - pytest ../test
    - mypy --config-file ../setup.cfg ../py_src

notifications:
    email: false
