os: linux
dist: bionic
language: python
python:
    - "3.6"  # current default on Travis CI
before_install:
    - cd py_src
install:
    - pip3 install -r requirements.txt
    - pip3 install ..
script:
    - pytest ../test
    - export MYPYPATH='./stubs'
    - mypy ../py_src

notifications:
    email: false
