os: linux
dist: bionic
language: python
python:
    - "3.6"  # current default on Travis CI
before_install:
    - cd py_src
install:
    - pip3 install -r requirements.txt
    - pip3 install -e ..
script:
    - export MYPYPATH='./stubs'
    - mypy ../py_src
    - flake8 ../py_src
    - docstr-coverage -m -f -F 80.0 ../py_src
after_success:
    - cd ../test
    - pytest --cov-config=.coveragerc --cov-report=xml --cov=../py_src
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
