os: linux
dist: bionic
language: python
python:
    - "3.6"  # current default on Travis CI
before_install:
    - cd py_src
install:
    - pip3 install -r requirements.txt
    - pip3 install ..
script:
    - export MYPYPATH='./stubs'
    - mypy ../py_src
after_success:
    - cd ..
    - export CODECOV_TOKEN="b3233ad7-de29-4752-b9cb-5dfcd0d9718c"
    - coverage run test/*.py
    - codecov

notifications:
    email: false
