# Minimal makefile for Sphinx documentation
# This file was autogenerated with sphinx-quickstart aside from custom
# `make doc` command for LaTeX and test for pytest testing

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = ./docs
BUILDDIR      = ./docs

# set SHELL to bash for target `test`:
test: export SHELL = /bin/bash

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

doc:
	@sphinx-build -M latexpdf ./docs/ ./docs/

# for codecov upload to work supply `export CODECOV_TOKEN=<token>` or -t <token>
# token can be found in settings either at codecov or travis-ci
test:
	echo 'export CODECOV_TOKEN set?'
	@cd test/ && pytest --cov-config=.coveragerc --cov-report=xml --cov-report=html --cov-report=annotate --cov=../py_src 1>>/dev/null && bash <(curl -s https://codecov.io/bash)

# remember that any new line in a Makefile is executed in a new shell; the
# @ makes only genuine output appear and suppresses the actual command:
lint:
	@cd py_src/ && export MYPYPATH='./stubs' && mypy --config-file ../setup.cfg ../py_src
	@flake8 py_src/ && echo 'flake8: success'
	@docstr-coverage -m -f -F 80.0 py_src

# Use something like @rm -rf <file> 2>>/dev/null || echo "does not exist" to
# remove <file> and receive an appropriate error if it does not exist
clean:
	@rm -rf py_src/__pycache__
	@rm -rf py_src/sub_module/__pycache__
	@rm -rf test/__pycache__
	@rm -rf docs/doctrees
	@mv ./docs/latex/packagingtest.pdf ./docs/main.pdf 2>>/dev/null || echo "no updated docs available"
	@rm -rf docs/latex
	@rm -rf docs/html
	@rm test/*.xml 2>>/dev/null || echo "no .xml file in test directory"
	@rm py_src/*,cover 2>>/dev/null || echo "no coverage files found"
	@rm py_src/sub_module/*,cover 2>>/dev/null || echo "no coverage files found"

.PHONY: help doc test lint clean Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
